# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title : Neastic - Blog
tagline: "The Neatastic blog"
github: [metadata]
author :
  name : Antoine Cordelois
  email : a.cordelois@neatastic.com
  github : eu
collections:
#  - members
lang: en
sass:
  sass_dir: assets/_sass
  style: compressed
paginate: 6
paginate_path: "/:num/"
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
production_url : http://blog.neatastic.com
compress_html:
  clippings: [div, p, ul, td, h1, h2]
  comments: ["<!-- ", " -->"]
  endings: [p, li, td]
  ignore:
    envs: []  # disable compression in dev environment
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - semantic/src
  - semantic/tasks
